"""empty message

Revision ID: 095efe51edb4
Revises: 27bfff1a4285
Create Date: 2025-11-29 11:16:28.206760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '095efe51edb4'
down_revision = '27bfff1a4285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=30), nullable=False))
        batch_op.drop_constraint(batch_op.f('pet_images_type_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('pet_images_username_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['url'])
        batch_op.drop_column('type')
        batch_op.drop_column('username')

    with op.batch_alter_table('pet_post', schema=None) as batch_op:
        batch_op.alter_column('found_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_post', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('found_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('pet_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('pet_images_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('pet_images_type_key'), ['type'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('url')

    # ### end Alembic commands ###
