"""empty message

Revision ID: 27bfff1a4285
Revises: 0763d677d453
Create Date: 2025-11-28 19:36:25.961399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bfff1a4285'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('found_location', sa.String(length=30), nullable=False),
    sa.Column('actual_location', sa.String(length=120), nullable=False),
    sa.Column('found_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('breed', sa.String(length=30), nullable=False),
    sa.Column('physical_description', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actual_location'),
    sa.UniqueConstraint('found_location')
    )
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pet_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('pet_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_post_id'], ['pet_post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('prof_img', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('prof_img')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')
        batch_op.drop_column('address')
        batch_op.drop_column('username')

    op.drop_table('pet_images')
    op.drop_table('social_media')
    op.drop_table('pet_post')
    # ### end Alembic commands ###
