"""empty message

Revision ID: 5ca84c15c48d
Revises: 9f9911ad86ee
Create Date: 2025-12-11 19:17:13.338697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca84c15c48d'
down_revision = '9f9911ad86ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pet_post_actual_location_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('pet_post_found_location_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_post', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('pet_post_found_location_key'), ['found_location'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('pet_post_actual_location_key'), ['actual_location'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
