"""empty message

Revision ID: 6e165697b97d
Revises: d45b2ba0bdc5
Create Date: 2025-12-11 14:31:33.314162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e165697b97d'
down_revision = 'd45b2ba0bdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_post', schema=None) as batch_op:
        batch_op.alter_column('physical_description',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_post', schema=None) as batch_op:
        batch_op.alter_column('physical_description',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
