"""empty message

Revision ID: fc8d07012eb0
Revises: bb89ceb86e37
Create Date: 2025-12-14 16:14:02.646175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8d07012eb0'
down_revision = 'bb89ceb86e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_post', schema=None) as batch_op:
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_post', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
